import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: true,
    },
    {
      name: 'John Doe',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: false,
    },
    {
      name: 'Sarah Khan',
      email: 'sarah@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: false,
    },
    {
      name: 'Amit Sharma',
      email: 'amit@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: false,
    },
    {
      name: 'Priya Singh',
      email: 'priya@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality slim fit Nike shirt.',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 8,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 15,
      description: 'Premium Adidas shirt for daily wear.',
    },
    {
      name: 'Puma Casual Shirt',
      slug: 'puma-casual-shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 140,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.0,
      numReviews: 7,
      description: 'Comfortable Puma casual shirt.',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 95,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 12,
      description: 'Slim fit Nike pant.',
    },
    {
      name: 'Adidas Sport Pant',
      slug: 'adidas-sport-pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 110,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 6,
      description: 'Sporty Adidas pant.',
    },
    {
      name: 'Puma Joggers',
      slug: 'puma-joggers',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 80,
      countInStock: 9,
      brand: 'Puma',
      rating: 4.4,
      numReviews: 9,
      description: 'Soft and comfortable joggers.',
    },
    {
      name: 'Reebok Running Shoes',
      slug: 'reebok-running-shoes',
      category: 'Shoes',
      image: '/images/p7.jpg',
      price: 220,
      countInStock: 12,
      brand: 'Reebok',
      rating: 4.8,
      numReviews: 20,
      description: 'Lightweight running shoes.',
    },
    {
      name: 'Nike Air Max',
      slug: 'nike-air-max',
      category: 'Shoes',
      image: '/images/p8.jpg',
      price: 300,
      countInStock: 6,
      brand: 'Nike',
      rating: 4.9,
      numReviews: 30,
      description: 'Popular Nike Air Max sneakers.',
    },
    {
      name: 'Adidas Hoodie',
      slug: 'adidas-hoodie',
      category: 'Jackets',
      image: '/images/p9.jpg',
      price: 180,
      countInStock: 4,
      brand: 'Adidas',
      rating: 4.3,
      numReviews: 11,
      description: 'Warm and stylish hoodie.',
    },
    {
      name: 'Puma Winter Jacket',
      slug: 'puma-winter-jacket',
      category: 'Jackets',
      image: '/images/p10.jpg',
      price: 260,
      countInStock: 3,
      brand: 'Puma',
      rating: 4.7,
      numReviews: 14,
      description: 'Perfect winter jacket.',
    },
    {
      name: 'Levis Denim Jacket',
      slug: 'levis-denim-jacket',
      category: 'Jackets',
      image: '/images/p11.jpg',
      price: 240,
      countInStock: 7,
      brand: 'Levis',
      rating: 4.5,
      numReviews: 18,
      description: 'Classic denim jacket.',
    },
    {
      name: 'Under Armour Shorts',
      slug: 'under-armour-shorts',
      category: 'Shorts',
      image: '/images/p12.jpg',
      price: 70,
      countInStock: 10,
      brand: 'Under Armour',
      rating: 4.2,
      numReviews: 5,
      description: 'Comfortable sports shorts.',
    },
    {
      name: 'Nike Training Shorts',
      slug: 'nike-training-shorts',
      category: 'Shorts',
      image: '/images/p13.jpg',
      price: 85,
      countInStock: 11,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 8,
      description: 'Breathable training shorts.',
    },
  ],
};

export default data;
